### ISSUE TITLE
Clicking on links in the navigation component does not change the URL or render the corresponding component.

### ISSUE THREAD

**Issue by Beauty-ku-mari** [Beauty-ku-mari/Frontend-Development#4]
Solution: Make sure you are using the BrowserRouter from react-router-dom to wrap your application and the Link or NavLink components for navigation.

**Comment by TrickyVikram** [comment]
Please assign this to me

**Comment by Beauty-ku-mari** [comment]
ok

**Comment by Beauty-ku-mari** [comment]
done
